### ISSUE TITLE
Is there a way to undo a memoized property in a subclass?

### ISSUE THREAD

**Issue by quidproquo** [estebistec/python-memoized-property#3]
I have an issue when I override a memoized property in a subclass, where it just defaults to the super classes value. Is there an easy way to de-memoize a property?

**Comment by estebistec** [comment]
I tried:
```python
class Base(object):
  @memoized_property
  def val(self):
    return 1

class Thing(Base):
  @property
  def val(self):
    return id(self)
```

and then ran these examples:
```
>>> b = Base()
>>> b.val
1
>>> t = Thing()
>>> t.val
140055777103208
```

How are you overriding the base property?
